/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.7 .\hani_avatar_netural.gltf
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/hani_avatar_netural.gltf')
  return (
    <group {...props} dispose={null}>
      <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
        <mesh geometry={nodes.eye_highlight_heart.geometry} material={materials.lambert4} />
        <mesh geometry={nodes.EYE_LEFT.geometry} material={materials.lambert1} position={[1.189, 2.935, -9.104]} rotation={[-0.004, -0.06, -0.303]} scale={[1.133, 0.192, 1.133]} />
        <mesh geometry={nodes.EYE_RIGHT.geometry} material={materials.lambert1} position={[1.189, 2.935, -9.104]} rotation={[-0.004, -0.06, -0.303]} scale={[1.133, 0.192, 1.133]} />
        <mesh geometry={nodes.eyebrow_LEFT.geometry} material={materials.lambert1} position={[1.18, 2.226, -10.55]} rotation={[0, 0, -0.431]} scale={[0.822, 1, 0.156]} />
        <mesh geometry={nodes.eyebrow_RIGHT.geometry} material={materials.lambert1} position={[1.18, 2.226, -10.55]} rotation={[0, 0, -0.431]} scale={[0.822, 1, 0.156]} />
        <mesh geometry={nodes.LASH_LEFT.geometry} material={materials.lambert1} position={[1.569, 2.794, -9.361]} rotation={[-0.922, 0.569, 0.617]} scale={[0.443, 0.195, 0.1]} />
        <mesh geometry={nodes.LASH_RIGHT.geometry} material={materials.lambert1} position={[1.569, 2.794, -9.361]} rotation={[-0.922, 0.569, 0.617]} scale={[0.443, 0.195, 0.1]} />
        <mesh geometry={nodes.mouth_hani_.geometry} material={materials.lambert1} position={[0, 3.536, -8.213]} rotation={[0.265, 0, 0]} scale={[1, 0.067, 0.111]} />
        <mesh geometry={nodes.nose.geometry} material={materials.lambert1} position={[0, 3.49, -8.574]} scale={[0.288, 0.16, 0.16]} />
      </group>
      <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
        <mesh geometry={nodes.Mesh009.geometry} material={materials.lambert_rabbit} />
        <mesh geometry={nodes.Mesh009_1.geometry} material={materials.lambert_innerear} />
      </group>
    </group>
  )
}

useGLTF.preload('/hani_avatar_netural.gltf')
